# Generated by Django 6.1 on 2026-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of restaurant')),
                ('city', models.CharField(max_length=100, verbose_name='city of restaurant')),
            ],
        ),
    ]
